/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-02-07 at 09:14:57 UTC 
 * Modify at your own risk.
 */

package com.jtristan.reservarestaurante.entidad.reservaendpoint.model;

/**
 * Model definition for Reserva.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the reservaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Reserva extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Usuario> comensales;

  static {
    // hack to force ProGuard to consider Usuario used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Usuario.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime horaReserva;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numeroPersonas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Restaurante restaurante;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Usuario usuario;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Usuario> getComensales() {
    return comensales;
  }

  /**
   * @param comensales comensales or {@code null} for none
   */
  public Reserva setComensales(java.util.List<Usuario> comensales) {
    this.comensales = comensales;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getHoraReserva() {
    return horaReserva;
  }

  /**
   * @param horaReserva horaReserva or {@code null} for none
   */
  public Reserva setHoraReserva(com.google.api.client.util.DateTime horaReserva) {
    this.horaReserva = horaReserva;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Reserva setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumeroPersonas() {
    return numeroPersonas;
  }

  /**
   * @param numeroPersonas numeroPersonas or {@code null} for none
   */
  public Reserva setNumeroPersonas(java.lang.Integer numeroPersonas) {
    this.numeroPersonas = numeroPersonas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Restaurante getRestaurante() {
    return restaurante;
  }

  /**
   * @param restaurante restaurante or {@code null} for none
   */
  public Reserva setRestaurante(Restaurante restaurante) {
    this.restaurante = restaurante;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Usuario getUsuario() {
    return usuario;
  }

  /**
   * @param usuario usuario or {@code null} for none
   */
  public Reserva setUsuario(Usuario usuario) {
    this.usuario = usuario;
    return this;
  }

  @Override
  public Reserva set(String fieldName, Object value) {
    return (Reserva) super.set(fieldName, value);
  }

  @Override
  public Reserva clone() {
    return (Reserva) super.clone();
  }

}
